name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: dir "${{ github.workspace }}" 

  testing:
    runs-on: windows-latest
    steps:
    - run: Write-Host "Test1a enviroment var $GITHUB_REPOSITORY"
      shell: powershell
    - run: Write-Host "Test1b enviroment var ${{ github.run_number }}"
      shell: powershell
    - run: Write-Host "Test1c condition var ${{ github.repository }}"
      shell: powershell
    - run: Write-Host "Test2a enviroment var $RUNNER_OS"
      shell: powershell
    - run: Write-Host "Test2b condition var ${{ runner.os }}"
      shell: powershell
    - run: Write-Host "Test3a enviroment var $RUNNER_OS"
      if: runner.os == 'Linux'
      shell: powershell
    - run: Write-Host "Test3b condition var ${{ runner.os }}"
      if: runner.os == 'Windows'
      shell: powershell
    - run: git clone https://github.com/samsmithnz/CherryPicking.git

