name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: Write-Host "Test1 enviroment var $GITHUB_REPOSITORY"
      shell: powershell
    - run: Write-Host "Test1b enviroment var ${{GitHub.Repository}}"
      shell: powershell
    - run: Write-Host "Test2 condition var ${{github.repository}}"
      shell: powershell
    - run: Write-Host "Test1b enviroment var $RUNNER_OS"
      shell: powershell
    - run: Write-Host "Test2 condition var ${{runner.os}}"
      shell: powershell
