name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: Write-Host "Test1 enviroment var ${ GITHUB_REF }"
      shell: powershell
    - run: Write-Host "Test2 condition var ${ github.ref }"
      shell: powershell
