name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: Write-Host "Test1 enviroment var ${GITHUB_WORKFLOW}"
      shell: powershell
    - run: Write-Host "Test1b enviroment var ${GitHub_WorkFlow}"
      shell: powershell
    - run: Write-Host "Test2 condition var ${github.workflow}"
      shell: powershell
